name: gymm
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher:  ^6.3.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  curved_navigation_bar: ^1.0.6
  awesome_dialog: ^3.2.1
  fwfh_url_launcher: ^0.9.1
  emoji_picker_flutter: ^3.1.0
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/img.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img.png"
